name: Create Dependency Bump PR
on:
    workflow_dispatch:
    schedule:
        - cron: '0 8 * * 4'

permissions:
    contents: write
    pull-requests: write

jobs:
    bump-bounds:
        runs-on: ubuntu-latest
        steps:
            - uses: nomeata/haskell-bounds-bump-action@main
              with:
                test: true
